name: Testing Module Resolution

on:
  push:
    branches:
      - module-resolution-testing

jobs:
  run-module-resolution-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, windows-2022, ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      # Note: using pnpm --filter '@flarelabs-net/*' doesn't seem to work on windows for some reason, so we need
      #       to build in the package directory instead of using the build:packages script from the root
      - name: Build Cloudflare environment provider Package
        shell: bash
        run: pnpm build
        working-directory: ./packages/vite-environment-provider-cloudflare

      - name: Run tests
        shell: bash
        run: DEBUG_DUMPS=true pnpm --filter cloudflare-dev-module-resolution-fixture test

      - name: Log
        if: always()
        shell: bash
        run: ls ./fixtures/cloudflare-dev-module-resolution/.workerd-env-dumps

      - name: Upload all debug dumps
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-dumps-00-${{matrix.os}}
          path: ./fixtures/cloudflare-dev-module-resolution/.workerd-env-dumps/**/*

      - name: Upload debug dumps 0
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-dumps-00-${{matrix.os}}
          path: ./fixtures/cloudflare-dev-module-resolution/.workerd-env-dumps/dev_run_00

      - name: Upload debug dumps 1
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-dumps-01-${{matrix.os}}
          path: ./fixtures/cloudflare-dev-module-resolution/.workerd-env-dumps/dev_run_01

      - name: Upload debug dumps 2
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-dumps-02-${{matrix.os}}
          path: ./fixtures/cloudflare-dev-module-resolution/.workerd-env-dumps/dev_run_02
